const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('api', {
  loadData:       ()      => ipcRenderer.invoke('data:load'),
  saveData:       (data)  => ipcRenderer.invoke('data:save', data),
  exportPath:     ()      => ipcRenderer.invoke('data:export-path'),
  exportExcel:    (filePath, items) => ipcRenderer.invoke('data:export', { filePath, items }),
  openDataFolder: ()      => ipcRenderer.invoke('data:open-location'),
  fetchAO3:       (url)   => ipcRenderer.invoke('ao3:fetch', url),
  fetchFFNet:     (url)   => ipcRenderer.invoke('ffnet:fetch', url),
  ao3Login:       ()      => ipcRenderer.invoke('ao3:login'),
  ao3LoggedIn:    ()      => ipcRenderer.invoke('ao3:logged-in'),
  openExternal:   (url)   => ipcRenderer.invoke('shell:open-external', url),
  gitStatus:      ()      => ipcRenderer.invoke('git:status'),
  gitBackup:      ()      => ipcRenderer.invoke('git:backup'),
  pullData:       ()      => ipcRenderer.invoke('git:pull-data'),
  fetchBook:      (q)     => ipcRenderer.invoke('books:fetch', q),
  openLocalFile:  (path)  => ipcRenderer.invoke('files:open-local', path),
  pickLocalFile:  (defaultPath) => ipcRenderer.invoke('files:pick-local', defaultPath),
  checkFiles:     (paths) => ipcRenderer.invoke('files:check', paths),
  locateFile:     (name)  => ipcRenderer.invoke('files:locate', name),
  relinkFiles:    (items) => ipcRenderer.invoke('files:relink', items),
  fetchImage:     (url)   => ipcRenderer.invoke('net:fetch-image', url),
  getBookDescription: (title, author) => ipcRenderer.invoke('books:description', { title, author }),
})
